name: Workflow

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  review-warnings-and-build:
    name: "Source files are prettified, then verify if build is possible"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        name: Yarn Cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        working-directory: ./
        continue-on-error: false
        run: |
          yarn install

      - name: Check if Files are Prettified
        working-directory: ./
        continue-on-error: false
        run: |
          ./check-prettier.sh

      - name: Check if build is correct
        working-directory: ./
        continue-on-error: false
        run: |
          yarn build