name: Docs Workflow
on:
  push:
    branches:
      - master
    paths: ["dist/**"] # Trigger the action only when dist files have changed
jobs:
  build-and-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: If commit is a release, then we build a new storybook
        if: contains(github.event.head_commit.message, 'Release') # If commit message is from a Release, we will deploy a new page version
        run: | # Install npm packages and build the Storybook files
          yarn install
          yarn run build-storybook
      - name: Deploy github pages
        if: contains(github.event.head_commit.message, 'Release')
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: docs-build # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # The folder that we serve our Storybook files from